//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionSeguridad.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int UsuarioID { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
