//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionSeguridad.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicaciones
    {
        public int UbicacionID { get; set; }
        public int UsuarioID { get; set; }
        public int ProvinciaID { get; set; }
        public int CantonID { get; set; }
        public int DistritoID { get; set; }
        public string OtrasSenias { get; set; }
    
        public virtual Cantones Cantones { get; set; }
        public virtual Distritos Distritos { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
